name: climatify
description: "climatify project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  animate_do: ^2.1.0
  bloc: ^8.0.0
  cached_network_image: ^3.2.1
  country_picker: ^2.0.27
  country_state_city: ^0.1.6
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^4.0.6
  dropdown_button2: ^2.3.9
  dropdown_search: ^6.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.2.0
  flutter_reaction_button: ^3.0.0+3
  flutter_svg: ^2.0.14
  flutter_translate: ^4.1.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  share_plus: ^10.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  story_view: ^0.16.5
  url_launcher: ^6.2.6
  vs_story_designer: ^2.2.0
